#Definitions of steps for pipeline
definitions:
  steps:
    - step: &test-step
        name: Test
        script:
          - npm install
          - npm test

    - step: &build-step
        name: Build and Push Docker Image
        image: google/cloud-sdk:latest
        script:
          - echo $GCLOUD_API_KEYFILE > ~/.gcloud-api-key.json
          - gcloud auth activate-service-account --key-file ~/.gcloud-api-key.json
          - gcloud auth configure-docker --quiet
          - export IMAGE_NAME=gcr.io/$GCLOUD_PROJECT_ID/$BITBUCKET_REPO_SLUG:$BITBUCKET_COMMIT
          - docker build -t $IMAGE_NAME .
          - docker push $IMAGE_NAME
        services:
          - docker

    - step: &build-fake
        name: Build and Push Docker Image
        image: google/cloud-sdk:latest
        script:
          - echo "Build and push Docker image to container registry"
          - IMAGE_NAME=gcr.io/${GCLOUD_PROJECT_ID}/${BITBUCKET_REPO_SLUG}:${BITBUCKET_COMMIT}
          - echo ${BITBUCKET_REPO_SLUG}
          - echo ${IMAGE_NAME}

    - step: &deploy-stage-step
        name: Deploy Staging
        deployment: staging
        script:
          - sed -i "s|{{image}}|gcr.io/$GCLOUD_PROJECT_ID/$BITBUCKET_REPO_SLUG:$BITBUCKET_COMMIT|g" simple-app.yml
          - sed -i "s|{{replicas}}|1|g" simple-app.yml
          - echo $GCLOUD_API_KEYFILE | base64 > KEY_FILE
          - pipe: atlassian/google-gke-kubectl-run:1.3.1
            variables:
              KEY_FILE: '$KEY_FILE'
              PROJECT: '$GCLOUD_PROJECT_ID'
              COMPUTE_ZONE: '$GCLOUD_ZONE'
              CLUSTER_NAME: '$GCLOUD_CLUSTER_NAME'
              KUBECTL_COMMAND: 'apply'
              RESOURCE_PATH: 'simple-app.yml'

    - step: &deploy-stage-fake
        name: Deploy Staging
        deployment: staging
        script:
          - echo "Deploy to staging environment"

    - step: &deploy-prod-step
        name: Deploy Production
        deployment: production
        script:
          - sed -i "s|{{image}}|gcr.io/$GCLOUD_PROJECT_ID/$BITBUCKET_REPO_SLUG:$BITBUCKET_COMMIT|g" simple-app.yml
          - sed -i "s|{{replicas}}|3|g" simple-app.yml
          - echo $GCLOUD_API_KEYFILE | base64 > KEY_FILE          
          - pipe: atlassian/google-gke-kubectl-run:1.3.1
            variables:
              KEY_FILE: '$KEY_FILE'
              PROJECT: '$GCLOUD_PROJECT_ID'
              COMPUTE_ZONE: '$GCLOUD_ZONE'
              CLUSTER_NAME: '$GCLOUD_CLUSTER_NAME'
              KUBECTL_COMMAND: 'apply'
              RESOURCE_PATH: 'simple-app.yml'

    - step: &deploy-prod-fake
        name: Deploy Production
        deployment: production
        script:
          - echo "Deploy to production environment"



image : node:14

pipelines:
  default:
    - step: *test-step
    - step: *build-fake
#    - step: *build-step

  pull-requests:
    '**':
      - step: *test-step
      - step: *build-fake
      - step: *deploy-stage-fake
#      - step: *build-step
#      - step: *deploy-stage-step
  branches:
    master:
      - step: *test-step
      - step: *build-fake
      - step: *deploy-prod-fake
#      - step: *build-step
#      - step: *deploy-prod-step
    production:
      - step: *test-step
      - step: *build-fake
      - step: *deploy-prod-fake
#      - step: *build-step
#      - step: *deploy-prod-step