apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  selector:
    matchLabels:
      app: simple-app
  replicas: {{replicas}}
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
        - name: simple-app
          image: {{image}}
          ports:
            - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: simple-app-entrypoint
spec:
  selector:
    app: simple-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000